#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("rct_helper_android.Resource", IsApplication=true)]

namespace rct_helper_android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int Input_file = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Input_file_check = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Output_file = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Output_file_check = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Start = 2130968580;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int button_Input_file_check_default = 2130903041;
			
			// aapt resource value: 0x7f030003
			public const int button_Input_file_check_fail = 2130903043;
			
			// aapt resource value: 0x7f030002
			public const int button_Input_file_check_ok = 2130903042;
			
			// aapt resource value: 0x7f030004
			public const int button_Output_file_check_default = 2130903044;
			
			// aapt resource value: 0x7f030006
			public const int button_Output_file_check_fail = 2130903046;
			
			// aapt resource value: 0x7f030005
			public const int button_Output_file_check_ok = 2130903045;
			
			// aapt resource value: 0x7f030007
			public const int button_Start_default = 2130903047;
			
			// aapt resource value: 0x7f030009
			public const int button_Start_fail = 2130903049;
			
			// aapt resource value: 0x7f030008
			public const int button_Start_ok = 2130903048;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
